apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: project-1
resources:
  - namespace/project-1.yaml
  - todo-app/cron-job.yaml
  - todo-app/deployment.yaml
  - todo-app/ingress.yaml
  - todo-app/service.yaml
  - todo-app/analysistemplate.yaml
  - secrets/secret.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - broadcaster/deployment.yaml
images:
  - name: todo-app-image
    newName: velivalentine/todo-app@sha256:834735a3c2861096c4030ef5155e78a215270f2f691c44d97ad92a76cfe849b2
  - name: postgres-image
    newName: postgres@sha256:84c6ea4333ae18f25ea0fb18bb142156f2a2e545e0a779d93bbf08079e56bdaf
  - name: broadcaster-image
    newName: velivalentine/broadcaster@sha256:5c0ef4e2face3ed5b54181e2f3c40d111ba0bfcb44f2a258f112272822dd5bae