apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: space-1
  labels:
    app: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgres-app
  ports:
    - port: 5432
      name: web
