apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: space-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs
      containers:
        - name: log-output
          image: log-output-image

          resources:
            limits:
              cpu: "200m"
              memory: "100Mi"

          volumeMounts:
            - mountPath: /usr/src/logs
              name: shared-logs

          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /
              port: 3000

          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: MESSAGE
            - name: LOG_PATH
              value: "/usr/src/logs/shared.log"
            - name: PING_PONG_URL
              value: http://ping-pong-app-service:2345/

        - name: log-writer
          image: log-writer-image
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
          volumeMounts:
            - mountPath: /usr/src/logs
              name: shared-logs
          env:
            - name: LOG_PATH
              value: "/usr/src/logs/shared.log"
