apiVersion: v1
kind: Service
metadata:
  name: log-output-service
  namespace: space-1
spec:
  type: NodePort
  selector:
    app: log-output
  ports:
    - name: http
      port: 2345
      protocol: TCP
      targetPort: 3000