apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-todo
  namespace: project-1
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: daily-todo-app
              image: velivalentine/daily-todo@sha256:cc56041383b940ef1bcd950b0cacb743beeb01cb52ad4f16a404ab3c09825762
              imagePullPolicy: IfNotPresent
              env:
                - name: TODO_URL
                  value: "http://todo-app-service:2345/todos"
          restartPolicy: Never
