apiVersion: v1
kind: Service
metadata:
  name: ping-pong-app-service
  namespace: space-1
spec:
  type: NodePort
  selector:
    app: ping-pong-app
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3001